.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "BLUEPRINTIGNORE" "5" "December 2011" "DevStructure" "Blueprint"
.
.SH "NAME"
\fBblueprintignore\fR \- ignore specific resources when creating blueprints
.
.SH "SYNOPSIS"
.
.nf

/etc/foo
!foo/bar
baz*
:file:/etc/foobar
:package:apt/build\-essential
!:source:/opt
.
.fi
.
.SH "DESCRIPTION"
Lines in \fB/etc/blueprintignore\fR and \fB~/\.blueprintignore\fR are interpreted as in \fBblueprint\-rules\fR(5) but in a negative context \- rules enumerate resources to be ignored and \fB!\fR\-prefixed rules unignore resources\.
.
.P
As part of \fBblueprint\-create\fR(1), the \fB/etc/blueprintignore\fR and \fB~/\.blueprintignore\fR files that were used to create the blueprint are stored in the local blueprint repository\.
.
.P
There are many resources that are ignored by default\. These defaults are not meant to be an exhuastive list of exceptions and edge cases\. Rather, they\'re meant to cover typical base installations without hassle\.
.
.SS "Files"
The following files and directories are part of the default ignore list\. They can be negated using \fB!\fR just like any other pattern\.
.
.IP "\(bu" 4
\fB*~\fR
.
.IP "\(bu" 4
\fB*\.blueprint\-template\.*\fR
.
.IP "\(bu" 4
\fB*\.dpkg\-*\fR
.
.IP "\(bu" 4
\fB/etc/\.git\fR
.
.IP "\(bu" 4
\fB/etc/\.pwd\.lock\fR
.
.IP "\(bu" 4
\fB/etc/X11/default\-display\-manager\fR
.
.IP "\(bu" 4
\fB/etc/adjtime\fR
.
.IP "\(bu" 4
\fB/etc/alternatives\fR
.
.IP "\(bu" 4
\fB/etc/apparmor\fR
.
.IP "\(bu" 4
\fB/etc/apparmor\.d\fR
.
.IP "\(bu" 4
\fB/etc/blkid/blkid\.tab\fR
.
.IP "\(bu" 4
\fB/etc/ca\-certificates\.conf\fR
.
.IP "\(bu" 4
\fB/etc/console\-setup\fR
.
.IP "\(bu" 4
\fB/etc/dpkg/origins/default\fR
.
.IP "\(bu" 4
\fB/etc/fstab\fR
.
.IP "\(bu" 4
\fB/etc/group\-\fR
.
.IP "\(bu" 4
\fB/etc/group\fR
.
.IP "\(bu" 4
\fB/etc/gshadow\-\fR
.
.IP "\(bu" 4
\fB/etc/gshadow\fR
.
.IP "\(bu" 4
\fB/etc/hostname\fR
.
.IP "\(bu" 4
\fB/etc/init\.d/\.legacy\-bootordering\fR
.
.IP "\(bu" 4
\fB/etc/initramfs\-tools/conf\.d/resume\fR
.
.IP "\(bu" 4
\fB/etc/ld\.so\.cache\fR
.
.IP "\(bu" 4
\fB/etc/localtime\fR
.
.IP "\(bu" 4
\fB/etc/lvm/cache\fR
.
.IP "\(bu" 4
\fB/etc/mailcap\fR
.
.IP "\(bu" 4
\fB/etc/mtab\fR
.
.IP "\(bu" 4
\fB/etc/modules\fR
.
.IP "\(bu" 4
\fB/etc/motd\fR
.
.IP "\(bu" 4
\fB/etc/network/interfaces\fR
.
.IP "\(bu" 4
\fB/etc/passwd\-\fR
.
.IP "\(bu" 4
\fB/etc/passwd\fR
.
.IP "\(bu" 4
\fB/etc/popularity\-contest\.conf\fR
.
.IP "\(bu" 4
\fB/etc/prelink\.cache\fR
.
.IP "\(bu" 4
\fB/etc/resolv\.conf\fR
.
.IP "\(bu" 4
\fB/etc/rc\.d\fR
.
.IP "\(bu" 4
\fB/etc/rc0\.d\fR
.
.IP "\(bu" 4
\fB/etc/rc1\.d\fR
.
.IP "\(bu" 4
\fB/etc/rc2\.d\fR
.
.IP "\(bu" 4
\fB/etc/rc3\.d\fR
.
.IP "\(bu" 4
\fB/etc/rc4\.d\fR
.
.IP "\(bu" 4
\fB/etc/rc5\.d\fR
.
.IP "\(bu" 4
\fB/etc/rc6\.d\fR
.
.IP "\(bu" 4
\fB/etc/rcS\.d\fR
.
.IP "\(bu" 4
\fB/etc/shadow\-\fR
.
.IP "\(bu" 4
\fB/etc/shadow\fR
.
.IP "\(bu" 4
\fB/etc/ssh/ssh_host_key*\fR
.
.IP "\(bu" 4
\fB/etc/ssh/ssh_host_*_key*\fR
.
.IP "\(bu" 4
\fB/etc/ssl/certs\fR
.
.IP "\(bu" 4
\fB/etc/sysconfig/clock\fR
.
.IP "\(bu" 4
\fB/etc/sysconfig/i18n\fR
.
.IP "\(bu" 4
\fB/etc/sysconfig/keyboard\fR
.
.IP "\(bu" 4
\fB/etc/sysconfig/network\fR
.
.IP "\(bu" 4
\fB/etc/sysconfig/network\-scripts\fR
.
.IP "\(bu" 4
\fB/etc/timezone\fR
.
.IP "\(bu" 4
\fB/etc/udev/rules\.d/70\-persistent\-*\.rules\fR
.
.IP "\(bu" 4
\fB/etc/yum\.repos\.d\fR
.
.IP "" 0
.
.P
The following files are ignored if their content matches an expected hash\. They can be negated using \fB!\fR just like any other pattern\. These comparisions are made to augment searching files from packages to handle files that are part of packages but are not explicitly listed\.
.
.IP "\(bu" 4
\fB/etc/adduser\.conf\fR
.
.IP "\(bu" 4
\fB/etc/apparmor\.d/tunables/home\.d/ubuntu\fR
.
.IP "\(bu" 4
\fB/etc/apt/apt\.conf\.d/00CDMountPoint\fR
.
.IP "\(bu" 4
\fB/etc/apt/apt\.conf\.d/00trustcdrom\fR
.
.IP "\(bu" 4
\fB/etc/chatscripts/provider\fR
.
.IP "\(bu" 4
\fB/etc/default/console\-setup\fR
.
.IP "\(bu" 4
\fB/etc/default/grub\fR
.
.IP "\(bu" 4
\fB/etc/default/irqbalance\fR
.
.IP "\(bu" 4
\fB/etc/default/keyboard\fR
.
.IP "\(bu" 4
\fB/etc/default/locale\fR
.
.IP "\(bu" 4
\fB/etc/default/rcS\fR
.
.IP "\(bu" 4
\fB/etc/environment\fR
.
.IP "\(bu" 4
\fB/etc/hosts\.allow\fR
.
.IP "\(bu" 4
\fB/etc/hosts\.deny\fR
.
.IP "\(bu" 4
\fB/etc/initramfs\-tools/modules\fR
.
.IP "\(bu" 4
\fB/etc/inputrc\fR
.
.IP "\(bu" 4
\fB/etc/iscsi/iscsid\.conf\fR
.
.IP "\(bu" 4
\fB/etc/kernel\-img\.conf\fR
.
.IP "\(bu" 4
\fB/etc/ld\.so\.conf\fR
.
.IP "\(bu" 4
\fB/etc/ld\.so\.conf\.d/nosegneg\.conf\fR
.
.IP "\(bu" 4
\fB/etc/networks\fR
.
.IP "\(bu" 4
\fB/etc/nsswitch\.conf\fR
.
.IP "\(bu" 4
`/etc/nsswitch\.conf
.
.IP "\(bu" 4
\fB/etc/pam\.d/common\-account\fR
.
.IP "\(bu" 4
\fB/etc/pam\.d/common\-auth\fR
.
.IP "\(bu" 4
\fB/etc/pam\.d/common\-password\fR
.
.IP "\(bu" 4
\fB/etc/pam\.d/common\-session\fR
.
.IP "\(bu" 4
\fB/etc/pam\.d/common\-session\-noninteractive\fR
.
.IP "\(bu" 4
\fB/etc/pam\.d/fingerprint\-auth\-ac\fR
.
.IP "\(bu" 4
\fB/etc/pam\.d/fingerprint\-auth\fR
.
.IP "\(bu" 4
\fB/etc/pam\.d/password\-auth\-ac\fR
.
.IP "\(bu" 4
\fB/etc/pam\.d/password\-auth\fR
.
.IP "\(bu" 4
\fB/etc/pam\.d/smartcard\-auth\-ac\fR
.
.IP "\(bu" 4
\fB/etc/pam\.d/smartcard\-auth\fR
.
.IP "\(bu" 4
\fB/etc/pam\.d/system\-auth\-ac\fR
.
.IP "\(bu" 4
\fB/etc/pam\.d/system\-auth\fR
.
.IP "\(bu" 4
\fB/etc/ppp/chap\-secrets\fR
.
.IP "\(bu" 4
\fB/etc/ppp/pap\-secrets\fR
.
.IP "\(bu" 4
\fB/etc/ppp/peers/provider\fR
.
.IP "\(bu" 4
\fB/etc/profile\fR
.
.IP "\(bu" 4
\fB/etc/python/debian_config\fR
.
.IP "\(bu" 4
\fB/etc/rc\.local\fR
.
.IP "\(bu" 4
\fB/etc/rsyslog\.d/50\-default\.conf\fR
.
.IP "\(bu" 4
\fB/etc/security/opasswd\fR
.
.IP "\(bu" 4
\fB/etc/selinux/restorecond\.conf\fR
.
.IP "\(bu" 4
\fB/etc/selinux/targeted/modules/semanage\.trans\.LOCK\fR
.
.IP "\(bu" 4
\fB/etc/selinux/targeted/modules/active/file_contexts\.template\fR
.
.IP "\(bu" 4
\fB/etc/selinux/targeted/modules/active/file_contexts\fR
.
.IP "\(bu" 4
\fB/etc/selinux/targeted/modules/active/users_extra\fR
.
.IP "\(bu" 4
\fB/etc/selinux/targeted/modules/active/*\.pp\fR
.
.IP "\(bu" 4
\fB/etc/selinux/targeted/modules/active/netfilter_contexts\fR
.
.IP "\(bu" 4
\fB/etc/selinux/targeted/modules/active/seusers\.final\fR
.
.IP "\(bu" 4
\fB/etc/selinux/targeted/modules/active/file_contexts\.homedirs\fR
.
.IP "\(bu" 4
\fB/etc/selinux/targeted/modules/active/commit_num\fR
.
.IP "\(bu" 4
\fB/etc/selinux/targeted/modules/active/policy\.kern\fR
.
.IP "\(bu" 4
\fB/etc/selinux/targeted/modules/active/homedir_template\fR
.
.IP "\(bu" 4
\fB/etc/selinux/targeted/modules/semanage\.read\.LOCK\fR
.
.IP "\(bu" 4
\fB/etc/selinux/targeted/contexts/failsafe_context\fR
.
.IP "\(bu" 4
\fB/etc/selinux/targeted/contexts/virtual_domain_context\fR
.
.IP "\(bu" 4
\fB/etc/selinux/targeted/contexts/removable_context\fR
.
.IP "\(bu" 4
\fB/etc/selinux/targeted/contexts/netfilter_contexts\fR
.
.IP "\(bu" 4
\fB/etc/selinux/targeted/contexts/userhelper_context\fR
.
.IP "\(bu" 4
\fB/etc/selinux/targeted/contexts/virtual_image_context\fR
.
.IP "\(bu" 4
\fB/etc/selinux/targeted/contexts/securetty_types\fR
.
.IP "\(bu" 4
\fB/etc/selinux/targeted/contexts/default_type\fR
.
.IP "\(bu" 4
\fB/etc/selinux/targeted/contexts/dbus_contexts\fR
.
.IP "\(bu" 4
\fB/etc/selinux/targeted/contexts/files/file_contexts\fR
.
.IP "\(bu" 4
\fB/etc/selinux/targeted/contexts/files/file_contexts\.homedirs\fR
.
.IP "\(bu" 4
\fB/etc/selinux/targeted/contexts/files/media\fR
.
.IP "\(bu" 4
\fB/etc/selinux/targeted/contexts/initrc_context\fR
.
.IP "\(bu" 4
\fB/etc/selinux/targeted/contexts/x_contexts\fR
.
.IP "\(bu" 4
\fB/etc/selinux/targeted/contexts/customizable_types\fR
.
.IP "\(bu" 4
\fB/etc/selinux/targeted/contexts/users/xguest_u\fR
.
.IP "\(bu" 4
\fB/etc/selinux/targeted/contexts/users/unconfined_u\fR
.
.IP "\(bu" 4
\fB/etc/selinux/targeted/contexts/users/staff_u\fR
.
.IP "\(bu" 4
\fB/etc/selinux/targeted/contexts/users/root\fR
.
.IP "\(bu" 4
\fB/etc/selinux/targeted/contexts/users/user_u\fR
.
.IP "\(bu" 4
\fB/etc/selinux/targeted/contexts/users/guest_u\fR
.
.IP "\(bu" 4
\fB/etc/selinux/targeted/contexts/default_contexts\fR
.
.IP "\(bu" 4
\fB/etc/selinux/targeted/policy/policy\.24\fR
.
.IP "\(bu" 4
\fB/etc/selinux/targeted/setrans\.conf\fR
.
.IP "\(bu" 4
\fB/etc/selinux/targeted/seusers\fR
.
.IP "\(bu" 4
\fB/etc/selinux/config\fR
.
.IP "\(bu" 4
\fB/etc/selinux/restorecond_user\.conf\fR
.
.IP "\(bu" 4
\fB/etc/selinux/semanage\.conf\fR
.
.IP "\(bu" 4
\fB/etc/sgml/xml\-core\.cat\fR
.
.IP "\(bu" 4
\fB/etc/shells\fR
.
.IP "\(bu" 4
\fB/etc/ssh/sshd_config\fR
.
.IP "\(bu" 4
\fB/etc/sudoers\fR
.
.IP "\(bu" 4
\fB/etc/ufw/after\.rules\fR
.
.IP "\(bu" 4
\fB/etc/ufw/after6\.rules\fR
.
.IP "\(bu" 4
\fB/etc/ufw/before\.rules\fR
.
.IP "\(bu" 4
\fB/etc/ufw/before6\.rules\fR
.
.IP "\(bu" 4
\fB/etc/ufw/ufw\.conf\fR
.
.IP "" 0
.
.SS "Packages"
All APT\- or Yum\-managed packages considered essential to the system are part of the default ignore list\.
.
.P
Debian packages that are listed as \fBessential\fR, \fBimportant\fR, \fBrequired\fR, or \fBstandard\fR and those that are depended upon by \fBubuntu\-minimal\fR, \fBubuntu\-standard\fR, or \fBubuntu\-desktop\fR are ignored\.
.
.P
Yum packages that are part of the \fBbase\fR, \fBcore\fR, or \fBgnome\-desktop\fR groups are ignored\.
.
.SS "Sources"
By default, all directories except \fB/usr/local\fR are ignored as source resources\. If it is necessary to build and install software from source in another directory, use a negated source resource such as \fI!:source:/opt\fR\.
.
.SH "FILES"
.
.TP
\fB~/\.blueprints\.git\fR
The local repsitory where blueprints are stored, each on its own branch\.
.
.TP
\fB/etc/blueprintignore\fR, \fB~/\.blueprintignore\fR
Lists of filename patterns to be ignored when creating blueprints\.
.
.TP
\fB/tmp/blueprint\-apt\-exclusions\fR, \fB/tmp/blueprint\-yum\-exclusions\fR
The lists of APT\- and Yum\-managed packages considered essential\.
.
.TP
\fB/tmp/blueprintignore\fR
A cached copy of the complete list of ignore rules\.
.
.SH "THEME SONG"
The Flaming Lips \- "The W\.A\.N\.D\. (The Will Always Negates Defeat)"
.
.SH "AUTHOR"
Richard Crowley \fIrichard@devstructure\.com\fR
.
.SH "SEE ALSO"
Part of \fBblueprint\fR(1)\.
