.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "BLUEPRINT" "5" "May 2011" "DevStructure" "Blueprint"
.
.SH "NAME"
\fBblueprint\fR \- blueprint JSON format
.
.SH "SYNOPSIS"
.
.nf

{
  "packages": {
    "MANAGER": {
      "PACKAGE": ["VERSION"],
      "PACKAGE": ["VERSION", "VERSION"]
    },
    "MANAGER": {
      "PACKAGE": ["VERSION"],
      "PACKAGE": ["VERSION"]
    }
  },
  "files": {
    "PATHNAME": {
      "owner": "OWNER",
      "group": "GROUP",
      "mode": "MODE",
      "content": "CONTENT",
      "encoding": "ENCODING"
    }
  },
  "sources": {
    "DIRNAME": "FILENAME"
  },
  "arch": "ARCHITECTURE"
}
.
.fi
.
.P
(Keys and values written in CAPITALS represent variable data\.)
.
.SH "DESCRIPTION"
\fBblueprint\-create\fR(1) commits \fBblueprint\.json\fR to the appropriate branch in the local blueprint repository\. The format described here is used to generate Puppet modules, Chef cookbooks, and POSIX shell scripts in \fBblueprint\-show\fR(1) and \fBblueprint\-apply\fR(1)\.
.
.SS "Packages"
Each key within the \fBpackages\fR names a package manager\. Each manager contains keys that name packages to be installed by that manager\. Each package name is associated with an array of versions that should be installed\. In most cases, for most managers, this array will have only one element\.
.
.P
Each manager is itself the name of a package that appears elsewhere\. \fBpackages\fR should be processed by starting with the \fBapt\fR manager, installing its dependencies\. Any manager that was installed during this pass should next have its dependencies installed, continuing recursively until all managers and all dependencies have been installed\.
.
.SS "Files"
Each key in the optional \fBfiles\fR object is the fully\-qualified pathname to a file\. The associated value contains the \fBowner\fR, owning \fBgroup\fR, \fBmode\fR (a string containing the full 6\-digit octal representation), \fBcontent\fR, and the \fBencoding\fR of content (one of \fIplain\fR or \fIbase64\fR)\.
.
.SS "Sources"
Each key in the optional \fBsources\fR object is the fully\-qualified path to a directory\. The associated value is the name of a tarball of the contents of that directory at the time the blueprint was created\. It should be extracted there when the blueprint is applied\. The tarball is stored in Git alongside \fBblueprint\.json\fR and is included in Puppet modules and Chef cookbooks, and referenced from POSIX shell scripts\.
.
.SS "Architecture"
If \fBsources\fR is present and non\-empty, \fBarch\fR will also be present indicating the architecture of the server that created the blueprint\. If present, this value will be \fIamd64\fR or \fIi386\fR\.
.
.SH "THEME SONG"
The Flaming Lips \- "The W\.A\.N\.D\. (The Will Always Negates Defeat)"
.
.SH "AUTHOR"
Richard Crowley \fIrichard@devstructure\.com\fR
.
.SH "SEE ALSO"
\fBblueprint\fR(1)\.
