.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "BLUEPRINT\-RULES" "1" "December 2011" "DevStructure" "Blueprint"
.
.SH "NAME"
\fBblueprint\-rules\fR \- create a blueprint from a blueprint\-rules file
.
.SH "SYNOPSIS"
\fBblueprint rules\fR [\fB\-P\fR|\fB\-C\fR|\fB\-S\fR|\|\.\|\.\|\.] [\fB\-m\fR \fImessage\fR] [\fB\-r\fR] [\fB\-q\fR] [\fIpathname\fR]
.
.SH "DESCRIPTION"
\fBblueprint\-rules\fR renders the \fBblueprint\-rules\fR(5) file \fIpathname\fR and stores the resulting blueprint in a branch of the local blueprint repository with the commit \fImessage\fR (if given)\. The branch name is the basename of \fIpathname\fR with its extension (conventionally \fB\.blueprint\-rules\fR) removed\.
.
.P
If standard input is not a TTY or \fIpathname\fR is \fB\-\fR, rules are read from standard input\.
.
.P
The rendered blueprint will contain only the resources enumerated in \fIpathname\fR (or on standard input), opening the possibility of creating multiple orthogonal blueprints from the same system\.
.
.P
If one of \fB\-\-puppet\fR, \fB\-\-chef\fR, \fB\-\-bcfg2\fR, \fB\-\-sh\fR, or \fB\-\-cfn\fR is given, a Puppet module, a Chef cookbook, a bcfg2 repository, POSIX shell code, or an AWS CloudFormation template will be generated, written to a file or directory in the current working directory, and its filename will be printed to standard output\.
.
.SH "OPTIONS"
.
.TP
\fB\-P\fR, \fB\-\-puppet\fR
Generate a Puppet module\.
.
.TP
\fB\-C\fR, \fB\-\-chef\fR
Generate a Chef cookbook\.
.
.TP
\fB\-B\fR, \fB\-\-bcfg2\fR
Generate bcfg2 configuration\.
.
.TP
\fB\-S\fR, \fB\-\-sh\fR
Generate POSIX shell code\.
.
.TP
\fB\-\-cfn\fR
Generate an AWS CloudFormation template\.
.
.TP
\fB\-m\fR \fImessage\fR, \fB\-\-message=\fR\fImessage\fR
Commit message\.
.
.TP
\fB\-r\fR, \fB\-\-relaxed\fR
Relax version constraints in generated code\.
.
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Operate quietly\.
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show a help message\.
.
.SH "FILES"
.
.TP
\fB~/\.blueprints\.git\fR
The local repsitory where blueprints are stored, each on its own branch\.
.
.SH "THEME SONG"
The Flaming Lips \- "The W\.A\.N\.D\. (The Will Always Negates Defeat)"
.
.SH "AUTHOR"
Richard Crowley \fIrichard@devstructure\.com\fR
.
.SH "SEE ALSO"
Part of \fBblueprint\fR(1)\.
