.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "BLUEPRINT\-TEMPLATE" "1" "December 2011" "DevStructure" "Blueprint"
.
.SH "NAME"
\fBblueprint\-template\fR \- render mustache\.sh templates locally
.
.SH "SYNOPSIS"
\fBblueprint template\fR [\fB\-q\fR] \fIpathname\fR
.
.SH "DESCRIPTION"
\fBblueprint\-template\fR renders the template for the given \fIpathname\fR using the \fBmustache\.sh\fR template rendering engine\. The template for \fIpathname\fR must be stored in \fIpathname\fR\fB\.blueprint\-template\.mustache\fR\. Data meant only for \fIpathname\fR may be stored in \fIpathname\fR\fB\.blueprint\-template\.sh\fR, a \fBsource\fR\-able POSIX shell script\.
.
.P
Data meant for all templates may be stored in files ending in \fB\.sh\fR in \fB/etc/blueprint\-template\.d\fR, again as \fBsource\fR\-able POSIX shell scripts\. Blueprint comes with a selection of suitable data, see \fBblueprint\-template\fR(7)\.
.
.P
This program is meant for use during development and testing of templates; \fBblueprint\-apply\fR(1) and \fBblueprint\-show\fR(1) take care of rendering templates automatically\.
.
.SH "OPTIONS"
.
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Operate quietly\.
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show a help message\.
.
.SH "FILES"
.
.TP
\fB/etc/blueprint\-template\.d\fR
\fBsource\fR\-able POSIX shell scripts ending in \fB\.sh\fR that set environment variables for use in templates\.
.
.SH "THEME SONG"
The Flaming Lips \- "The W\.A\.N\.D\. (The Will Always Negates Defeat)"
.
.SH "AUTHOR"
Richard Crowley \fIrichard@devstructure\.com\fR
.
.SH "SEE ALSO"
Part of \fBblueprint\fR(1)\.
.
.P
\fBblueprint\-template\fR(5) for \fBmustache\.sh\fR template language syntax\.
.
.P
\fBblueprint\-template\fR(7) for built\-in template data\.
