.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "BLUEPRINT\-DESTROY" "1" "December 2011" "DevStructure" "Blueprint"
.
.SH "NAME"
\fBblueprint\-destroy\fR \- destroy a blueprint
.
.SH "SYNOPSIS"
\fBblueprint destroy\fR [\fB\-q\fR] \fIname\fR
.
.SH "DESCRIPTION"
\fBblueprint\-destroy\fR removes the blueprint \fIname\fR\. That is, it removes the branch \fIname\fR from the local blueprint repository\.
.
.SH "OPTIONS"
.
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Operate quietly\.
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show a help message\.
.
.SH "FILES"
.
.TP
\fB~/\.blueprints\.git\fR
The local repsitory where blueprints are stored, each on its own branch\.
.
.SH "THEME SONG"
The Flaming Lips \- "The W\.A\.N\.D\. (The Will Always Negates Defeat)"
.
.SH "AUTHOR"
Richard Crowley \fIrichard@devstructure\.com\fR
.
.SH "SEE ALSO"
Part of \fBblueprint\fR(1)\.
