.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "BLUEPRINT\-TEMPLATE" "1" "November 2011" "DevStructure" "Blueprint"
.
.SH "NAME"
\fBblueprint\-template\fR \-
.
.SH "SYNOPSIS"
\fBblueprint template\fR [\fB\-q\fR] [\fIpathname\fR]
.
.SH "DESCRIPTION"
FIXME
.
.SH "OPTIONS"
.
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Operate quietly\.
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show a help message\.
.
.SH "FILES"
.
.TP
\fB/etc/blueprint\-template\.d\fR
FIXME
.
.SH "THEME SONG"
The Flaming Lips \- "The W\.A\.N\.D\. (The Will Always Negates Defeat)"
.
.SH "AUTHOR"
Richard Crowley \fIrichard@devstructure\.com\fR
.
.SH "SEE ALSO"
Part of \fBblueprint\fR(1)\.
