.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "BLUEPRINT\-PRUNE" "1" "December 2011" "DevStructure" "Blueprint"
.
.SH "NAME"
\fBblueprint\-prune\fR \- select a subset of resources interactively
.
.SH "SYNOPSIS"
\fBblueprint prune\fR [\fB\-m\fR \fImessage\fR] [\fB\-q\fR] \fIsrc\fR \fIdest\fR
.
.SH "DESCRIPTION"
\fBblueprint\-prune\fR interactively selects a subset of the resources in \fIsrc\fR into \fIdest\fR\. Each resource is presented to the user and the user must indicate whether the resource should be included in \fIdest\fR\.
.
.P
The input provides full \fBreadline\fR(3) support but may not be piped from some other source\.
.
.SH "OPTIONS"
.
.TP
\fB\-m\fR \fImessage\fR, \fB\-\-message=\fR\fImessage\fR
Commit message\.
.
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Operate quietly\.
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show a help message\.
.
.SH "FILES"
.
.TP
\fB~/\.blueprints\.git\fR
The local repsitory where blueprints are stored, each on its own branch\.
.
.SH "THEME SONG"
The Flaming Lips \- "The W\.A\.N\.D\. (The Will Always Negates Defeat)"
.
.SH "AUTHOR"
Richard Crowley \fIrichard@devstructure\.com\fR
.
.SH "SEE ALSO"
Part of \fBblueprint\fR(1)\.
