.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "BLUEPRINT\-DIFF" "1" "December 2011" "DevStructure" "Blueprint"
.
.SH "NAME"
\fBblueprint\-diff\fR \- save the difference between two blueprints
.
.SH "SYNOPSIS"
\fBblueprint diff\fR [\fB\-m\fR \fImessage\fR] [\fB\-q\fR] \fIminuend\fR \fIsubtrahend\fR \fIdifference\fR
.
.SH "DESCRIPTION"
\fBblueprint\-diff\fR saves the difference between the blueprints \fIminuend\fR and \fIsubtrahend\fR as \fIdifference\fR\. Files, package versions, and source tarballs in \fIminuend\fR that either differ from their counterparts in \fIsubtrahend\fR or do not appear at all will be included in \fIdifference\fR\.
.
.SH "OPTIONS"
.
.TP
\fB\-m\fR \fImessage\fR, \fB\-\-message=\fR\fImessage\fR
Commit message\.
.
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Operate quietly\.
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show a help message\.
.
.SH "FILES"
.
.TP
\fB~/\.blueprints\.git\fR
The local repsitory where blueprints are stored, each on its own branch\.
.
.SH "THEME SONG"
The Flaming Lips \- "The W\.A\.N\.D\. (The Will Always Negates Defeat)"
.
.SH "AUTHOR"
Richard Crowley \fIrichard@devstructure\.com\fR
.
.SH "SEE ALSO"
Part of \fBblueprint\fR(1)\.
